apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Values.global.app }}
    env: {{ .Values.global.env }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.app }}
        env: {{ .Values.global.env }}
        project: {{ .Values.global.project }}
    spec:
      containers:
      - name: txm-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: DB_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: DB_USER
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: DB_NAME
          - name: DATABASE_URL
            value: "mysql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):3306/$(DB_NAME)"