apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{- include "timetrack.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.db.password | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  DB_HOST: {{ .Values.db.host | quote }}
  DB_NAME: {{ .Values.db.name | quote }}