apiVersion: v1
kind: Service
metadata:
  name: timetrack-service
  labels:
    {{- include "timetrack.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "timetrack.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001