global:
  app: txm-app
  env: dev
  project: timetrack-v5
  owner: orlando

image:
  repository: orlandonlyne/txm-time-track
  tag: "v5.0"

db:
  host: "txm-dev-db.ca76qu0mc5rh.us-east-1.rds.amazonaws.com"
  user: "admin"
  name: "txmtimetrack"
  # La password la pasaremos por comando o la hardcodeamos aqu√≠ si prefieres
  password: "xI%2AKP%211%5BJn%29bu%3FZIjqUC~Zr3hNEm"

#env:
#  DATABASE_URL: 'mysql://admin:7WD%21ffZNT%23H52fvRZN_U9T%21X%3EPVj@txm-dev-db.ca76qu0mc5rh.us-east-1.rds.amazonaws.com:3306/timetrack'

service:
  type: NodePort
  port: 80
  targetPort: 8001